
ARCHIVENAME=BLECertTool
7ZIP=C:\Program Files\7-Zip\7z.exe

all: BLETest.exe

CFLAGS = -nologo -EHsc -W3 -Icore/include -IBleApi -Ible_util -DPLATFORM_WINDOWS -D__OS_WIN

# Switching to default __stdcall calling convention. works around a bug in the Windows 8.0 Ble headers.
#  I have been told this causes problems with 
#  Windows Platform SDK 10, so please try without on that  (unsupported) platform.
CFLAGS = $(CFLAGS) -Gz

LDFLAGS = setupapi.lib ws2_32.lib

# Crypto code.
LIBMINCRYPT=dsa_sig.obj p256.obj p256_ec.obj p256_ecdsa.obj sha256.obj

dsa_sig.obj: core/libmincrypt/dsa_sig.c
        $(CC) -Dinline="" -D"dst[P256_NBYTES]"="*dst" -c $(CFLAGS) core/libmincrypt/dsa_sig.c

p256.obj: core/libmincrypt/p256.c
        $(CC) -c $(CFLAGS) core/libmincrypt/p256.c

p256_ec.obj: core/libmincrypt/p256_ec.c
        $(CC) -c $(CFLAGS) core/libmincrypt/p256_ec.c

p256_ecdsa.obj: core/libmincrypt/p256_ecdsa.c
        $(CC) -c $(CFLAGS) core/libmincrypt/p256_ecdsa.c

sha256.obj: core/libmincrypt/sha256.c
        $(CC) -c $(CFLAGS) core/libmincrypt/sha256.c

# BLE Api
BLEAPI_HEADER=BleApi/BleApi.h BleApi/BleApiError.h BleApi/BleApiWindows.h BleApi/fido_apduresponses.h BleApi/fido_ble.h BleApi/BleDevice.h
BLEAPI=BleApi.obj BleApiWindows.obj BleDevice.obj BleDeviceWindows.obj

BleApi.obj: BleApi/BleApi.cpp $(BLEAPI_HEADER)
	$(CXX) -c $(CFLAGS) BleApi/BleApi.cpp -Fo$@

BleApiWindows.obj: BleApi/BleApiWindows.cpp $(BLEAPI_HEADER)
	$(CXX) -c $(CFLAGS) BleApi/BleApiWindows.cpp -Fo$@

BleDevice.obj: BleApi/BleDevice.cpp $(BLEAPI_HEADER)
	$(CXX) -c $(CFLAGS) BleApi/BleDevice.cpp -Fo$@

BleDeviceWindows.obj: BleApi/BleDeviceWindows.h $(BLEAPI_HEADER)
	$(CXX) -c $(CFLAGS) BleApi/BleDeviceWindows.cpp -Fo$@

# utility tools.
ble_util.obj: ble_util/ble_util.cpp ble_util/ble_util.h
        $(CXX) -c $(CFLAGS) ble_util/ble_util.cpp -Fo$@

# Core test program.
BleApiTest.exe: BleApiTest/BleApiTest.cpp ble_util.obj $(BLEAPI)
        $(CXX) $(CFLAGS) BleApiTest/BleApiTest.cpp ble_util.obj $(BLEAPI) $(LDFLAGS)

# BLE Test
BLETEST=U2FTests.obj BLETransportTests.obj
U2FTests.obj: BLETest/U2FTests.cpp BLETest/U2FTests.h $(BLEAPI_HEADER)
	$(CXX) -c $(CFLAGS) BLETest/U2FTests.cpp -Fo$@

BLETransportTests.obj: BLETest/BLETransportTests.cpp BLETest/U2FTests.h $(BLEAPI_HEADER)
	$(CXX) -c $(CFLAGS) BLETest/BLETransportTests.cpp -Fo$@


# Actual BLE tests
BLETest.exe: BLETest/BLETest.cpp ble_util.obj $(BLEAPI) $(BLETEST) $(LIBMINCRYPT)
        $(CXX) $(CFLAGS) BLETest/BLETest.cpp ble_util.obj $(BLEAPI) $(BLETEST) $(LIBMINCRYPT) $(LDFLAGS) -Fe$@

clean:
	del *.exe *.obj

dist: BLECertTool.zip

BLECertTool.zip: BLETest.exe
	-rmdir /q /s $(ARCHIVENAME)
	mkdir $(ARCHIVENAME)
	xcopy /y BLETest.exe $(ARCHIVENAME)
	move  /y $(ARCHIVENAME)\BLETest.exe $(ARCHIVENAME)\BLETest.ex_
	xcopy /y LICENSE $(ARCHIVENAME)
	move $(ARCHIVENAME)\LICENSE $(ARCHIVENAME)\LICENSE.BLETest
	xcopy /y core\libmincrypt\NOTICE $(ARCHIVENAME)
	move $(ARCHIVENAME)\NOTICE $(ARCHIVENAME)\LICENSE.libmincrypt
	xcopy /y README $(ARCHIVENAME)
	-"$(7ZIP)" a -r -mx9 -tzip $(ARCHIVENAME).zip $(ARCHIVENAME)
